import { createActions } from 'redux-actions';

const START_EXPERIMENT = 'START_EXPERIMENT';
const SELECT_BLOCKS = 'SELECT_BLOCKS';
const UNSELECT_BLOCKS = 'UNSELECT_BLOCKS';
const UPDATE_EXPERIMENT_PATTERN = 'UPDATE_EXPERIMENT_PATTERN';

export default createActions(
	{
	},
	START_EXPERIMENT,
	SELECT_BLOCKS,
	UNSELECT_BLOCKS,
	UPDATE_EXPERIMENT_PATTERN
);
